version: "3"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      NODE_ENV: production
      POSTGRES_USER: '{{user}}'
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: '{{project_name}}'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: 
      - ./.env.docker

  db-migrations:
    image: ghcr.io/{{gh_username}}/{{project_name}}-db-migrations:latest
    depends_on:
      - postgres


volumes:
  pgdata: